version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3

executors:
  base:
    parameters: &parameters
      ruby:
        type: string
        default: "2.7"
    working_directory: &workdir ~/solidus
    environment: &environment
      DEFAULT_MAX_WAIT_TIME: 10
      SOLIDUS_RAISE_DEPRECATIONS: true
      CIRCLE_TEST_REPORTS: /tmp/test-results
      CIRCLE_ARTIFACTS: /tmp/test-artifacts
      BUNDLE_WITHOUT: "utils"
    docker:
      - image: &image cimg/ruby:<< parameters.ruby >>-browsers

  postgres:
    parameters: *parameters
    working_directory: *workdir
    environment:
      <<: *environment
      DB: postgresql
      DB_HOST: localhost
    docker:
      - image: *image
      - image: jhawthorn/circleci-postgres-fast
        environment:
          POSTGRES_USER: root

  mysql:
    parameters: *parameters
    working_directory: *workdir
    environment:
      <<: *environment
      DB: mysql
      DB_HOST: 127.0.0.1
      DB_USERNAME: root
    docker:
      - image: *image
      - image: cimg/mysql:5.7

  sqlite:
    parameters: *parameters
    working_directory: *workdir
    environment:
      <<: *environment
      DB: sqlite
    docker:
      - image: *image

commands:
  setup:
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: |
          gem install bundler -v"~> 2.1" --conservative
          bundle lock
      - restore_cache:
          keys:
            - solidus-gems-v3-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - solidus-gems-v3-{{ .Branch }}
            - solidus-gems-v3-master
            - solidus-gems-v3

      - run: |
          bundle config set path 'vendor/bundle'
          bundle check || bundle install
          bundle clean

      - save_cache:
          key: solidus-gems-v3-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test:
    steps:
      - run:
          name: Run Tests
          command: ./bin/build-ci test

      - store_artifacts:
          path: /tmp/test-artifacts
          destination: test-artifacts

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

# TODO: Integrate with `setup` when we deprecate support for Rails 6.1 (vips is the default from Rails 7)
  libvips:
    steps:
      - run:
          name: Install libvips
          command: sudo apt-get install -y libvips

jobs: {}

workflows:
  build:
    jobs: []
